name: Releases

on:
  push:
    branches:
      - main
jobs:
  job1:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      output1: ${{ steps.step1.outputs.test }}
      output2: ${{ steps.step2.outputs.test }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - id: step1
        shell: pwsh
        run: echo "::set-output name=test::hello"
      - id: step2
        shell: pwsh
        run: |
          get-childitem
          $manifestInfo = Import-PowerShellDataFile -Path ./src/SampleProject5/SampleProject5.psd1
          echo "::set-output name=test::$($manifestInfo.ModuleVersion)"
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Display the path
        shell: pwsh
        run: echo ${env:PATH}
      - name: Version Display
        shell: pwsh
        run: $PSVersionTable
      - name: Bootstrap
        shell: pwsh
        run: ./actions_bootstrap.ps1
      - name: Test and Build
        shell: pwsh
        run: Invoke-Build -File .\src\Test003.build.ps1
      - name: Get moduleversion
        shell: pwsh
        run: |
          $manifestInfo = Import-PowerShellDataFile -Path ./src/Test003/Test003.psd1
          echo "::set-output name=version::$($manifestInfo.ModuleVersion)"
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v5.6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          custom_tag: $version
      - name: Build Changelog
        id: github_release
        uses: mikepenz/release-changelog-builder-action@v2.4.1
        with:
          configuration: ".github/changelog_configuration.json"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create a GitHub release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{steps.github_release.outputs.changelog}}