name: Releases

on:
  push:
    branches:
      - main
jobs:
  job2:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Display the path
        shell: pwsh
        run: echo ${env:PATH}
      - name: Version Display
        shell: pwsh
        run: $PSVersionTable
      - name: Bootstrap
        shell: pwsh
        run: ./actions_bootstrap.ps1
      - name: Test and Build
        shell: pwsh
        run: Invoke-Build -File .\src\Test003.build.ps1
      - name: Get_moduleversion
        shell: pwsh
        run: |
          $manifestInfo = Import-PowerShellDataFile -Path ./src/Test003/Test003.psd1
          echo "::set-output name=version::$($manifestInfo.ModuleVersion)"
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v5.6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          custom_tag: ${{ steps.Get_moduleversion.outputs.version }}
      - name: Build Changelog
        id: github_release
        uses: mikepenz/release-changelog-builder-action@v2.4.1
        with:
          configuration: ".github/changelog_configuration.json"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create a GitHub release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{steps.github_release.outputs.changelog}}
          artifacts: "./src/Archive/*"
      - name: Publish to Powershell Gallery
        env:
          NUGET_KEY: ${{ secrets.POSHTESTGALLERY_API }}
        shell: pwsh
        run: |
          New-Item ./src/Artifacts/Test003 -ItemType DIRECTORY
          Move-Item ./src/Artifacts/Test003.ps* ./src/Artifacts/Test003 -force
          Move-Item ./src/Artifacts/en-US ./src/Artifacts/Test003 -Force
          Get-ChildItem ./src/Artifacts/Test003
          Publish-Module -Repository 'PSTestGallery' -Path ./src/Artifacts/Test003 -NuGetApiKey $env:NUGET_KEY -Verbose
