name: Releases

on:
  push:
    branches:
      - main

jobs:
  job1:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      output1: ${{ steps.step1.outputs.test }}
      output2: ${{ steps.step2.outputs.test }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - id: step1
        shell: pwsh
        run: echo "::set-output name=test::hello"
      - id: step2
        shell: pwsh
        run: |
          get-childitem
          $manifestInfo = Import-PowerShellDataFile -Path ./src/SampleProject5/SampleProject5.psd1
          echo "::set-output name=test::$($manifestInfo.ModuleVersion)"
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - id: step1
        shell: pwsh
        run: echo ${{needs.job1.outputs.output1}} ${{needs.job1.outputs.output2}}
      - id: step2
        uses: actions/checkout@v2
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v5.6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          custom_tag: ${{needs.job1.outputs.output2}}
      - name: Build Changelog
        id: github_release
        uses: mikepenz/release-changelog-builder-action@v2.4.1
        with:
          configuration: ".github/changelog_configuration.json"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create a GitHub release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{steps.github_release.outputs.changelog}}